refactoring how script/server should run

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -4,7 +4,19 @@ function jenkins_server {
   local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
   source "$shome/script/profile"
 
-  exec java -jar "$shome/vendor/jenkins.war"
+  if [[ "$#" == 0 ]]; then
+    set -- default
+  fi
+
+  case "${1:-}" in
+    default)
+      exec java -jar "$shome/vendor/jenkins.war"
+      ;;
+    *)
+      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
+      return 1
+      ;;
+  esac
 }
 
 jenkins_server "$@"
